### ISSUE TITLE
7Span: Incipit Tool Bugs (12/13 - 1/11/24)

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/7Span-Phase2#650]
- [ ] Fix the substitutions of characters (added 12/19)
Problem: words not highlighting
This incipit matches another incipit 
<እ> ምብዙሕ፡ ተአምሪሃ፡ ለእግዝእትነ፡ ... ስምዑኬ፤ አኃውየ፤ ዘንተ፤` ምስጢረ`፤ መንክረ፤ ...
and matched with
ስምዑኬ ፡ ኦ ፡ አኃውየ ፡ ዘንተ ፡ `ምሥጢረ` ፡ መንክረ ፡ ...
BUT the program did not highlight words that have the different s that we should treat as equivalent:
The ሥ in ምሥጢረ 
Should be treated the same as ስ in ምስጢረ
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/cabc2c92-8b36-4cc9-b42c-06160d0e9efc)

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/36cdd4b7-0036-431a-b30a-06d52e8a93ad)

- [x] Fix matches

When I paste in an incipit, it does not match itself, not all words are highlighted in orange, even though it is EXACTLY the same. 
Example:
I pasted in this incipit:
[ESP (UH) DMA-005](https://pemm.princeton.edu/manuscripts/ESdma005), f. 43r (1850-1949)
ወካዕበ ፡ ስምዑ ፡ ዘከመ ፡ ትቤሎ ፡ ለቴዎፍሎስ ፡ ሊቀ ፡ ጳጳሳት ፡ ስማዕ ፡ ኦቴዎፍሎስ ፡ ፍቁረ ፡ ወልድየ ፡ ወሶበ ፡ ሖርነ ፡ በውእቱ ፡ መዋዕል ፡ ውስተ ፡ ካልእ ፡ ሀገር ፡ ኀበ ፡ ሀሎ ፡ ምኵራበ ፡ ጣዖቶሙ ፡ ለግብጽ ፡ ወድቁ ፡ ምኵራባቲሆሙ ፡ ወተሰብሩ ፡ ጣዖታቲሆሙ ፡ ለለክፍሎሙ ፡ ወሞቱ ፡ ኵሎሙ ፡ ገነውተ ፡ አማልክተ ፡ ወመጽኡ ፡ ሶቤሃ ፡ አድባር ፡ ወፀጥልዕ ፡ ወአራዊት ፡ ወሰገዱ

and it doesn't match itself, ESP (UH) DMA-005
ወካዕበ ፡ ስምዑ ፡ ዘከመ ፡ ትቤሎ ፡ ለቴዎፍሎስ ፡ ሊቀ ፡ ጳጳሳት ፡ ስማዕ ፡ ኦቴዎፍሎስ ፡ ፍቁረ ፡ ወልድየ ፡ ወሶበ ፡ ሖርነ ፡ በውእቱ ፡ መዋዕል ፡ ውስተ ፡ ካልእ ፡ ሀገር ፡ ኀበ ፡ ሀሎ ፡ ምኵራበ ፡ ጣዖቶሙ ፡ ለግብጽ ፡ ወድቁ ፡ ምኵራባቲሆሙ ፡ ወተሰብሩ ፡ ጣዖታቲሆሙ ፡ ለለክፍሎሙ ፡ ወሞቱ ፡ ኵሎሙ ፡ ገነውተ ፡ አማልክተ ፡ ወመጽኡ ፡ ሶቤሃ ፡ አድባር ፡ ወፀጥልዕ ፡ ወአራዊት ፡ ወሰገዱ
1-C in the results should be entirely orange
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/6f9413e6-2114-4c5e-a6c0-4a33e929e9fa)

**Comment by WendyLBelcher** [comment]
- [ ] Do NOT prioritize first letters or words over later letter and words

I used an incipit from G-Vatican (BAV) 29, with the first word with <እ>
<እ> ምብዙሕ፡ ተአምሪሃ፡ ለእግዝእትነ፡ ... ስምዑኬ፤ አኃውየ፤ ዘንተ፤ ምስጢረ፤ መንክረ፤ ወመድምመ፤ ዘነገሩነ፤ አበዊነ፤ ቅዱሳን፤ ዘረከብዎ፤ ጽሑፍ፤ ውስተ፤ መጽሐፍት፨ ወይቤሉ፤ አመ፤ ይመጽእ፤ እግዚእነ፤ በዳግም፤ ምጽአቱ፤ በዓቢይ፤ ስብሐት፤ ምስለ፤ መለእክት፤ ወኃይለት፨ ወበንፍሐተ፤ ቀርን፤ ወይትነስኡ፤ ሙታን፤ 
Here is the entry in Directus:
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/e56b86c7-88cd-40e1-af19-5bdb05ce4c8c)

Here is the search result, which is wrong:

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/3a49eec4-5e20-4bf4-80fa-037d1dfb6a09)

Here is the search result, which gets the right result first, 42, when changed to እምብዙሕ

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/36c324c2-002a-415f-961f-72a48c34c766)

**Comment by WendyLBelcher** [comment]
- [ ] Fix breadcrumbs, they are not working 
Note: When click on Google Back, nothing happens

Further, is it ignoring order?
                       <እ> ምብዙሕ፡ ተአምሪሃ፡ ለእግዝእትነ፡ ... `ስምዑኬ`፤`` አኃውየ፤ ዘንተ፤ ምስጢረ፤ መንክረ፤ ወመድምመ፤ ዘነገሩነ፤ አበዊነ፤ ቅዱሳን፤ ዘረከብዎ፤ ጽሑፍ፤ ውስተ፤ መጽሐፍት፨ ወይቤሉ፤ አመ፤ ይመጽእ፤ እግዚእነ፤ በዳግም፤ ምጽአቱ፤ በዓቢይ፤ ስብሐት፤ ምስለ፤ መለእክት፤ ወኃይለት፨ ወበንፍሐተ፤ ቀርን፤ ወይትነስኡ፤ ሙታን፤ 
Canonical incipit: `ስምዑኬ `፡ ኦ ፡ አኃውየ ፡ ዘንተ ፡ ምሥጢረ` ፡` መንክረ ፡ ወመድምመ ፡ ዘነገሩነ ፡ አበዊነ ፡ ቅዱሳን ፡ ወይቤሉ ፡ አመ ፡ ይመጽእ ፡ በዳግም ፡ ምጽአቱ ፡ በስብሐት ፡ ምስለ ፡ መላ እክት ፡ ወኃይላት ፡ በንፍሐተ ፡ ቀርን ፡ ይትነሥኡ ፡ ምውታን ።

**Comment by WendyLBelcher** [comment]
- [ ] Do NOT omit matches simply because not that many words match
Note: ተአምሪሃ፡ ለእግዝእትነ are among the top ten most common words in incipits. So, `Records not found `is an impossible result, there are definitely results
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/cf5ed462-c965-4c4d-a8ee-bfd54cdf663e)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/4bee081c-30cb-4ced-8c57-b21537f29afd)

Also, ID 125
B-Gayant (EOTC) 1 incipit is
ወሀሎ፡ አሐዱ፡ ብእሲ፡ በሀገረ፡ ቀምር፡ ክቡረ፡ ዘመድ፡ በስምሰ፡ ክርስቲያናዊ፡ ወኀጢአቱ፡ ዐቢይ፡ ወፍዱል፡ እምኀጢአተ፡ ኵሉ፡ ሰብእ።
One word in this incipit appears in only 2 incipits in the database, ID 125 and one other. Words that are rare should be weighted more heavily
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/9dea6fe0-2121-48c6-ac2f-c6f68649751a)

**Comment by WendyLBelcher** [comment]
- [ ] Weight rare words more

See ID 125
B-Gayant (EOTC) 1 incipit is
ወሀሎ፡ አሐዱ፡ ብእሲ፡ በሀገረ፡ ቀምር፡ ክቡረ፡ ዘመድ፡ በስምሰ፡ ክርስቲያናዊ፡ ወኀጢአቱ፡ ዐቢይ፡ ወፍዱል፡ እምኀጢአተ፡ ኵሉ፡ ሰብእ።
One word in this incipit appears in only 2 incipits in the database (ID 125 and 622). Words that are rare should be weighted more heavily.
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/9dea6fe0-2121-48c6-ac2f-c6f68649751a)

**Comment by WendyLBelcher** [comment]
UNESCO (HMML) 8.1
ID 400
ወበአሐቲ ፡ ዕለት ፡ ይቤላ ፡ ክርስቶስ ፡ ለእሙ ፡ ድንግል ፡ ዓይኑ ፡ የዓቢ ፡ እምነ ፡ ኃዘናት ፡ ዘረከበኪ ፡ በእንቲአየ ፡ ወትቤሎ ፡ እግዝእትነ ፡ ቅድስት ፡ .... እሉ ፡ ፭ኀዘናት ፡፡የዓብዩ ፡ ወሶበ ፡ ተነበየ ፡ ስምዖን ፡ በቤተ ፡ መቅደስ

ወበአሐቲ ፡ ዕለት ፡ ይቤላ ፡ እግዚእነ ፡ ወመድኃኒነ ፡ ኢየሱስ ፡ ክርስቶስ ፡ ለወላዲቱ ፡ እግዝእትነ ...
[EMML (HMML) 4435](https://pemm.princeton.edu/manuscripts/EMML4435) (1891)

![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/d6a869c8-3dd9-4b65-8776-199dfff3bd47)

**Comment by WendyLBelcher** [comment]
DSAE (HMML) 14
ID 53
ወሀለወት፡ ቤተ፡ ክርስቲያን፡ ዘእግዝእትነ፡ ... ውስተ፡ ደብረ፡ ምጥማቅ፡ ወሀሎ፡ ውስቴታ፡ ኤላ፡ ዘውእቱ፡ ምዕላደ፡ ማየ፡ ወልማዶሙ፡ ለመነኮሳት፡ ለለኵሉ፡ ዓመት፡ እምቅድመ፡ ብጽሐተ፡ በዓል፡ የዓስቡ፡ ሰብአ፡ ወይሁብዎሙ፡ አግማለ፡ ወያመጽኡ፡ ሎሙ፡ ማየ፡ ወይመልእዎሙ፡ ለዒላት

Canonical incipit is
ወሀሎ ፡ ፩ደብር ፡ ቅዱስ ፡ ደብረ ፡ ምጥማቅ ፡ ቤተ ፡ ክርስቲያን ፡ ዘሕንጽት ፡ በስማ ፡ ለግዝእትነ ...
[ESP (UH) ATH-008](https://pemm.princeton.edu/manuscripts/ESath008), f. 25v (1900-1999)

But here, when shortened, it worked
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/45af1912-1d82-4dfd-9fa6-46a068b9236b)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/efdc7d50-753e-408e-afff-2b5177fda87b)

**Comment by WendyLBelcher** [comment]
## Ignore
Do NOT omit matches simply because not that many words match
Are we omitting some words from the search? Maybe words like ለእግዝእትነ are omitted?

Note: ተአምሪሃ፡ ለእግዝእትነ are among the top ten most common words in incipits. So, `Records not found `is an impossible result, there are definitely results
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/cf5ed462-c965-4c4d-a8ee-bfd54cdf663e)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/4bee081c-30cb-4ced-8c57-b21537f29afd)

Because, here a search for a single rare word worked: ምጥማቅ
DSAE (HMML) 14
ID 53
ወሀለወት፡ ቤተ፡ ክርስቲያን፡ ዘእግዝእትነ፡ ... ውስተ፡ ደብረ፡ ምጥማቅ፡ ወሀሎ፡ ውስቴታ፡ ኤላ፡ ዘውእቱ፡ ምዕላደ፡ ማየ፡ ወልማዶሙ፡ ለመነኮሳት፡ ለለኵሉ፡ ዓመት፡ እምቅድመ፡ ብጽሐተ፡ በዓል፡ የዓስቡ፡ ሰብአ፡ ወይሁብዎሙ፡ አግማለ፡ ወያመጽኡ፡ ሎሙ፡ ማየ፡ ወይመልእዎሙ፡ ለዒላት

Canonical incipit is
ወሀሎ ፡ ፩ደብር ፡ ቅዱስ ፡ ደብረ ፡ ምጥማቅ ፡ ቤተ ፡ ክርስቲያን ፡ ዘሕንጽት ፡ በስማ ፡ ለግዝእትነ ...
[ESP (UH) ATH-008](https://pemm.princeton.edu/manuscripts/ESath008), f. 25v (1900-1999)

And here, when shortened, it worked
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/45af1912-1d82-4dfd-9fa6-46a068b9236b)
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/efdc7d50-753e-408e-afff-2b5177fda87b)

**Comment by WendyLBelcher** [comment]
### Ignore
Algorithm should weight rare words more? (possible?)

See ID 125
B-Gayant (EOTC) 1 incipit is
ወሀሎ፡ አሐዱ፡ ብእሲ፡ በሀገረ፡ ቀምር፡ ክቡረ፡ ዘመድ፡ በስምሰ፡ ክርስቲያናዊ፡ ወኀጢአቱ፡ ዐቢይ፡ ወፍዱል፡ እምኀጢአተ፡ ኵሉ፡ ሰብእ።

The result is correct, ID 125:
![image](https://github.com/PrincetonPEMM/7Span-Phase2/assets/56000106/7e192874-6c24-41f4-9243-ce6240baeff2)

But one word in this incipit appears in only 2 incipits in the database (ID 125 and 622): ቀምር. Words that are rare should be weighted more heavily.

**Comment by WendyLBelcher** [comment]
- [ ] Fix the substitutions
This incipit matches another incipit 
<እ> ምብዙሕ፡ ተአምሪሃ፡ ለእግዝእትነ፡ ... ስምዑኬ፤ አኃውየ፤ ዘንተ፤` ምስጢረ`፤ መንክረ፤ ወመድምመ፤ ዘነገሩነ፤ አበዊነ፤ ቅዱሳን፤ ዘረከብዎ፤ ጽሑፍ፤ ውስተ፤ መጽሐፍት፨ ወይቤሉ፤ አመ፤ ይመጽእ፤ እግዚእነ፤ በዳግም፤ ምጽአቱ፤ በዓቢይ፤ ስብሐት፤ ምስለ፤ መለእክት፤ ወኃይለት፨ ወበንፍሐተ፤ ቀርን፤ ወይትነስኡ፤ ሙታን፤
and matched with
ስምዑኬ ፡ ኦ ፡ አኃውየ ፡ ዘንተ ፡ `ምሥጢረ` ፡ መንክረ ፡ ወመድምመ ፡ ዘነገሩነ ፡ አበዊነ ፡ ቅዱሳን ፡ ወይቤሉ ፡ አመ ፡ ይመጽእ ፡ በዳግም ፡ ምጽአቱ ፡ በስብሐት ፡ ምስለ ፡ መላ እክት ፡ ወኃይላት ፡ በንፍሐተ ፡ ቀርን ፡ ይትነሥኡ ፡ ምውታን ።
BUT it did not highlight words that have the different s that we should treat as equivalent:
The ሥ in ምሥጢረ 
Should be treated the same as ስ in ምስጢረ
